// <auto-generated />
namespace smartservicesapp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_RegCateprivacy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_RegCateprivacy));
        
        string IMigrationMetadata.Id
        {
            get { return "201609270906567_Add_Reg-Cate-privacy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
